kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: helm-external
  namespace: fleet-default
spec:
  repo: https://github.com/rancher/fleet-examples
  paths:
    - multi-cluster/helm-external
  targets:
    - name: test
      clusterSelector:
        matchLabels:
          env: test